services:
  - type: web
    name: mon-api
    env: java
    plan: free
    buildCommand: mvn clean package
    startCommand: java -jar target/api-0.0.1-SNAPSHOT.jar
    envVars:
      - key: PORT
        value: 8080